version: '3.8'

services:
  hospital-celulares-app:
    build:
      context: .
      dockerfile: dockerfile.dev
    working_dir: /app
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - '3014:3014'
    env_file:
      - .env
